### ISSUE TITLE
Fails to compile with Swift 5.1 on Linux

### ISSUE THREAD

**Issue by foscomputerservices** [amzn/smoke-aws#25]
smoke-aws does not compile using Swift 5.1 compiler on Linux.

# Repro Steps

1) docker run -ti swift:latest /bin/bash
2) apt-get update && apt-get install -y libssl-dev
3) git clone https://github.com/amzn/smoke-aws.git
4) cd smoke-aws
5) swift build | grep -v warning

# Expected

Successful compile

# Actual

/smoke-aws/.build/checkouts/XMLCoding/Sources/XMLCoding/XMLStackParser.swift:292:43: error: 'XMLParser' is unavailable: This type has moved to the FoundationXML module. Import that module to use it.
    func parserDidStartDocument(_ parser: XMLParser)

(and many more errors)

**Comment by tachyonics** [comment]
Thanks for raising this. I am starting to go through and add CI tests for Swift 5.1 for all the Smoke repositories so I will fix this in the next couple of days.

**Comment by tachyonics** [comment]
The issue is in one of our dependencies.

I have raised a PR to fix the compilation issue - https://github.com/LiveUI/XMLCoding/pull/17

**Comment by tachyonics** [comment]
Version 0.4.1 of XMLCoding includes the fix for compiling under Swift 5.1. If you update the version of this dependency, it should compile.

**Comment by tachyonics** [comment]
We now have CI tests that verify compilation under Swift 5.1. Resolving.
